apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ include "guacamole.fullname" . }}-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts: {{ .Values.guacamole.gateway.hosts }}
  - port:
      name: https
      number: 443
      protocol: HTTPS
    hosts: {{ .Values.guacamole.gateway.hosts }}
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.guacamole.gateway.tls.secretName }}