apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "guacamole.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    {{- range .Values.guacamole.gateway.hosts }}
    - "{{ . }}"
    {{- end }}
  gateways:
  # - {{ include "guacamole.fullname" . }}-ingress-gateway
  - istio-system/istio-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "guacamole.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80